-- CPX UI/feature migration. Run after 20260917_cpx_hardening.sql.

alter table public.profiles
  add column if not exists presence_status text not null default 'online',
  add column if not exists last_seen_at timestamptz;

alter table public.channels
  add column if not exists category text not null default 'GERAL',
  add column if not exists description text,
  add column if not exists icon text not null default 'voice';

update public.channels
set category = case
  when lower(name) like '%jogo%' then 'JOGOS'
  when lower(name) like '%reuni%' or lower(name) like '%dev%' then 'EQUIPE'
  else 'GERAL'
end
where category is null or category = '';

create table if not exists public.channel_messages (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.channels(id) on delete cascade,
  sender_id text not null,
  sender_name text not null,
  content text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.channel_messages enable row level security;
create index if not exists channel_messages_lookup_idx on public.channel_messages(channel_id,created_at desc);
create index if not exists channel_messages_active_idx on public.channel_messages(channel_id,created_at) where deleted_at is null;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id text,
  actor_name text,
  action text not null,
  target text,
  details text,
  created_at timestamptz not null default now()
);

alter table public.activity_logs enable row level security;
create index if not exists activity_logs_created_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_action_idx on public.activity_logs(action,created_at desc);

-- Keep the tables private to the API/service role. The browser talks to the Next API,
-- so no anonymous/authenticated policies are intentionally opened here.

create or replace function public.touch_presence(p_status text)
returns void
language plpgsql
security definer
set search_path=public
as $presence$
begin
  update public.profiles
  set presence_status = case when p_status in ('online','away','busy','offline') then p_status else 'online' end,
      last_seen_at = now()
  where id = auth.uid();
end;
$presence$;

revoke all on function public.touch_presence(text) from public;
